### ISSUE TITLE
IEC 104 Client connecting to 100s of devices

### ISSUE THREAD

**Issue by techparva** [mz-automation/lib60870.NET#9]
I am trying to write a client which will read data from 100s of IEC 104 servers (devices in the field).
I create multiple connections and interrogate periodically (1 minute or so).
I observe that data from only some devices is received while data from other devices does not show up on the log.
Do you have any example of how to interrogate multiple devices?

**Comment by mzillgith** [comment]
There is no explicit example for having multiple connections. But since each connection is independent from the others it should not make any difference when using multiple connections. Just make sure that the connections are all active (sending START DT after connecting - done automatically by the library with the default settings) and no other client activates a connection to the servers you are using.
